// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RacEquipe.Entity;

namespace RacEquipe.Migrations
{
    [DbContext(typeof(RacDataContext))]
    [Migration("20190316232731_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854");

            modelBuilder.Entity("RacEquipe.Models.Equipement", b =>
                {
                    b.Property<int>("EquipementId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("NumeroDeSerie");

                    b.HasKey("EquipementId");

                    b.ToTable("Equipement");
                });
#pragma warning restore 612, 618
        }
    }
}
